import { StyleSheet } from "react-native";
import { COLORS } from "../../utils";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    fontFamily: "Overpass_Reg",
    backgroundColor: "red",
  },
  searchCont: {
    width: "100%",
    backgroundColor: COLORS.white,
    height: 320,
    borderBottomStartRadius: 20,
    borderBottomEndRadius: 20,
    display: "flex",
    alignItems: "center",
  },
  searchBar: {
    backgroundColor: COLORS.white,
    width: "80%",
    marginTop: 40,
    height: 50,
    borderRadius: 20,
    elevation: 7,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
    paddingHorizontal: 15,
  },
  inputText: {
    fontSize: 18,
    color: COLORS.secondary,
    fontFamily: "Overpass_Reg",
    width: "75%",
    paddingHorizontal: 5,
  },
  recentTxt: {
    fontFamily: "Overpass_Bold",
    color: COLORS.secondary,
    marginTop: 25,
    marginRight: 200,
  },
  recentCont: {
    height: 50,
    width: "100%",
    marginVertical: 5,
    display: "flex",
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-around",
  },
  recentTxt1: {
    width: "50%",
    fontSize: 18,
    fontFamily: "Overpass_Bold",
  },
  btmCont: {
    height: 380,
    width: "100%",
    backgroundColor: "blue",
    zIndex: -1,
    marginTop: -30,
    position: "relative",
  },
  MapsImg: {
    width: "100%",
    height: "100%",
    marginLeft: -30,
  },
  RedLoc: {
    position: "absolute",
  },
  gpsCont: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    width: 48,
    height: 48,
    backgroundColor: COLORS.white,
    position: "absolute",
    zIndex: 3,
    bottom: 50,
    right: 10,
    elevation: 5,
    borderRadius: 50,
  },
});
